version: 0.2
phases:
  pre_build:
    commands:
      - npm install --force
      - npm install -g npm@latest 
  build:
    commands:
      - npm run build
      
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
